version: '3'
services: 
  user:
    image: node:10.15.3-alpine
    volumes:
      - ./services/user/:/app
    working_dir: /app
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=user
      - JWT_SECRET=__JWT_SECRET_KEY__
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    command: npm run dev
    #  - /bin/bash
    #  - -c
    #  - |
    #    npm install yarn -g
    #    yarn install
    #    yarn dev 
  article:
    image: node:10.15.3-alpine
    volumes:
      - ./services/article/:/app
    working_dir: /app
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=article
      - JWT_SECRET=__JWT_SECRET_KEY__
    ports:
      - 3001:80
    depends_on:
      - mongodb  
    command: npm run dev
    #  - /bin/bash
    #  - -c
    #  - |
    #    npm install yarn -g
    #    yarn install
    #    yarn dev  
  web: 
    image: node:10.15.3-alpine
    volumes:
      - ./services/web/:/app
    working_dir: /app
    environment:
      - PORT=3000
      - JWT_SECRET=__JWT_SECRET_KEY__
      - ARTICLE_API_PATH=http://article
    ports:
      - 80:3000
    depends_on:
      - mongodb    
    command: npm run dev
    #  - /bin/bash
    #  - -c
    #  - |
    #    npm install yarn -g
    #    yarn install
    #    yarn dev            
  web_dashboard: 
    image: node:10.15.3-alpine
    volumes:
      - ./services/web-dashboard/:/app
    working_dir: /app
    environment:
      - PORT=3000
      - JWT_SECRET=__JWT_SECRET_KEY__
      - ARTICLE_API_PATH=http://article:3001
      - USER_API_PATH=http://user:3000
    ports:
      - 8080:3000
    
    command: npm run dev
    #  - /bin/bash
    #  - -c
    #  - |
    #    npm install yarn -g
    #    yarn install
    #    yarn dev                  
  mongodb:
    image: mongo:latest
    container_name: 'mongodatabase'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null